#!/bin/bash

#   This hook is invoked by git-commit[1] and git-merge[1], and can be bypassed
# with the --no-verify option. It takes a single parameter, the name of the
# file that holds the proposed commit log message. Exiting with a non-zero
# status causes the command to abort.
#   The hook is allowed to edit the message file in place, and can be used to
# normalize the message into some project standard format. It can also be used
# to refuse the commit after inspecting the message file.

set -Eeo pipefail

# Global hook
if [[ -n "$GIT_HOOK_DISABLE_SV4GIT" ]]
then
    git sv vcm --path "$PWD" --file "$1"
fi

# Local hook
LOCAL_HOOK="$PWD/.git/hooks/$(basename "$0")"
if [[ -e "$LOCAL_HOOK" ]]
then
    command sh "$LOCAL_HOOK" "$@"
fi
