#!/bin/bash

# This hook is invoked by git-commit[1], and can be bypassed with the
# --no-verify option. It takes no parameters, and is invoked before obtaining
# the proposed commit log message and making a commit. Exiting with a non-zero
# status from this script causes the git commit command to abort before
# creating a commit.

set -Eeo pipefail

# Global hook
# ...

# Local hook
LOCAL_HOOK="$PWD/.git/hooks/$(basename "$0")"
if [[ -e "$LOCAL_HOOK" ]]
then
    command sh "$LOCAL_HOOK" "$@"
fi
