---
version: "1.1"  # config version

versioning:  # versioning bump
    update-major: []  # Commit types used to bump major.
    update-minor:  # Commit types used to bump minor.
        - feat
    update-patch:  # Commit types used to bump patch.
        - build
        - ci
        - chore
        - docs
        - fix
        - perf
        - refactor
        - style
        - test
    # When type is not present on update rules and is unknown (not mapped on commit message types);
    # if ignore-unknown=false bump patch, if ignore-unknown=true do not bump version
    ignore-unknown: false

tag:
    pattern: '%d.%d.%d'  # Pattern used to create git tag.

release-notes:
    sections:  # Headers names for release notes markdown. To disable a section just remove the header line.
        - name: Features
          section-type: commits
          commit-types: [feat]
        - name: Bug Fixes
          section-type: commits
          commit-types: [fix]
        - name: Breaking Changes
          section-type: breaking-changes

branches:  # Git branches config.
    prefix: ([a-z]+\/)?  # Prefix used on branch name, it should be a regex group.
    suffix: (-.*)?  # Suffix used on branch name, it should be a regex group.
    disable-issue: true  # Set true if there is no need to recover issue id from branch name.
    skip: []  # List of branch names ignored on commit message validation.
    #     - master
    #     - main
    #     - developer
    skip-detached: false  # Set true if a detached branch should be ignored on commit message validation.

commit-message:
    types:  # Supported commit types.
        - build
        - ci
        - chore
        - docs
        - feat
        - fix
        - perf
        - refactor
        - revert
        - style
        - test
    scope:
        # Define supported scopes, if blank, scope will not be validated, if not, only scope listed will be valid.
        # Don't forget to add "" on your list if you need to define scopes and keep it optional.
        values: []
    footer:
        issue:  # Use "issue: {}" if you wish to disable issue footer.
            key: jira  # Name used to define an issue on footer metadata.
            key-synonyms:  # Supported variations for footer metadata.
                - Jira
                - JIRA
            use-hash: false  # If false, use :<space> separator. If true, use <space># separator.
    issue:
        regex: '[A-Z]+-[0-9]+'  # Regex for issue id.
