theme = "native"
icons = "awesome"

# DualShock 4
[[block]]
block = "battery"
driver = "upower"
device = "gaming_input_sony_controller_battery_d0obcoc1ob2o00o81"
allow_missing = true
hide_missing = true
icons_format = ' '

# M590 Logitech Mouse
[[block]]
block = "bluetooth"
mac = "F2:89:D1:3F:C6:77"
hide_disconnected = true

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

# Audio output volume
[[block]]
block = "sound"
driver = "pulseaudio"
device_kind = "sink"
on_click = "pactl set-sink-mute @DEFAULT_SINK@ toggle"
show_volume_when_muted = true

# Microphone volume
[[block]]
block = "sound"
driver = "pulseaudio"
device_kind = "source"
on_click = "pactl set-source-mute @DEFAULT_SOURCE@ toggle"
show_volume_when_muted = true

[[block]]
block = "battery"
driver = "upower"
device = "DisplayDevice"
full_threshold = 79

[[block]]
block = "taskwarrior"

# CodeStats score for last 12 hours
[[block]]
block = "custom"
command = ''' curl -s 'https://codestats.net/api/users/liljaylj' | jq -r '" \(.new_xp)"' '''
on_click = "xdg-open https://codestats.net/users/liljaylj"
interval = 300

[[block]]
block = "keyboard_layout"
driver = "sway"
[block.mappings]
"English (US)" = "EN"
"Russian (Kazakhstan, with Kazakh)"= "RU"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"
